server:
  port: 8080

security:
  sessions: ALWAYS
spring:
  session:
    store-type: redis
    ignored:
    - "*.bundle.*"
  redis:
    host: localhost
    password: "{cipher}02c58011d022ab9267a7814f213efb0aa36c149b29c5a585c0c4fa1b5d7b916f"
    port: 6379
  jpa: 
    properties: 
     hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  datasource: 
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.36:5432/microservice
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      connection-init-sql: SELECT 1
      auto-commit: false
      idle-timeout: 0
      pool-name: bbbpPool

zuul:
  routes:
    test:
      path: /redirect/**
      url: http://google.com
    collection:
     path: /collection/**
     url: http://localhost:8092
     sensitiveHeaders: Authorization, Set-Cookie
    dashboard:
     path: /dashboard/**
     url: http://localhost:8090
     sensitiveHeaders: Authorization, Set-Cookie
    web:
      path: /ui/**
      url: http://localhost:8091
      sensitiveHeaders: Authorization, Set-Cookie
  
   
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate: INFO
    com.zaxxer.hikari: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
#https://github.com/brettwooldridge/HikariCP
# HikariCP settings (one of the fastest production ready connection pool)
#For production environment,please set spring.datasource.hikari.maximum-pool-size=120 to 120 connections.
#spring.datasource.hikari.connection-timeout is 60000 = 1 minute , request will wait to take connection from pool,else sql exception will be thrown.



    